### ISSUE TITLE
Støtte alle "peker på meg" relasjoner

### ISSUE THREAD

**Issue by matsjs** [Informasjonsforvaltning/fdk-fulltext-search#106]
- [x] Legg til "isDescribedAt" på publicservicesmapping
- [x] Legg til "isClassifiedBy" på publicservicesmapping
- [x]  Legg til "requires" på publicservicesmapping
- [x]  Legg til "relation" på publicservicesmapping
- [x] Legg til "seeAlso" på conceptsmapping
- [x]  Legg til "isPartOf/hasPart/isReplacedBy/replaces" på infomodellmapping
- [x]  Legg til "isPartOf/hasPart/isReplacedBy/replaces" som infomodellspørring
- [ ] Bygg indeks på nytt

**Comment by shenluna** [comment]
Lukker saken, dette blir testet i https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/178
