### ISSUE TITLE
Reduser testtid i fdk-fulltext-search

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-fulltext-search#141]
Atm kjøres alle integrasjonstester dobbelt, både ila `integration_tests` og `contract_tests`. Reduser mengden tester i `contract_tests`, det er bare nødvendig å teste at gunicorn-config fungerer.

**Comment by lillelars** [comment]
Kvalitetsdirektøren melder at denne skal på museum.
