### ISSUE TITLE
Støtte and og or filter som input fra bruker

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-fulltext-search#149]
I dag er det hardkoda at vi bruker `and` når vi filterer på tema. 

Vi bør støtte at bruker oppgir om det skal brukes `and` eller `or`.

**Comment by oyvindis** [comment]
Vi kan angi filter direkte for et felt på en generell måte som vi gjør i dag:
{
               "collection": {
			"field": "distribution.mediaType.code.keyword",
			"values": ["application/json", "text/xml"]
		}
}

Hvis vi på et slikt filter kan angi en operator f.eks. slik:
{
               "collection": {
			"field": "distribution.mediaType.code.keyword",
			"values": ["application/json", "text/xml"],
                        "operator": "OR"
		}
}

Default operator "AND".
