### ISSUE TITLE
Kartverkets API'er og infomodeller får ny høstingsdato hver dag(?)

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-fulltext-search#15]
I PROD:
en gammel bug - kartverkets apier får ny publiseringsdato nesten hver dag (finner ikke igjen i github) som er mer synlig og ødelegger for Sist publisert på forsiden. Den burde fikses.

Gjenskap
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/a09b6c1e-4345-480d-8fd0-8588772995b8)

**Comment by lillelars** [comment]
@valosnah det er API'ene som får ny publiseringsdato hvert døgn. Infomodellene tar med seg denne datoen ettersom de blir generert ut fra API'et.

**Comment by valosnah** [comment]
@lillelars Det ser ut som dette ble løst da ny høster tok over. Sliter litt med å finne infomodeller som tilhører statens kartverk ... er det de som tilhører SVV?

**Comment by lillelars** [comment]
Denne ser ut som fungerer korrekt nå ja. Testet i prod :)
