### ISSUE TITLE
Verifiser at tema er med i søk

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-fulltext-search#151]
Tema skal, etter det eg forstår, vere med i søk. Ting tyder på at dette ikkje er tilfelle.

@oystein-asnes Kan du vere snill å kome opp med eit døme?

**Comment by oystein-asnes** [comment]
Test 1: Datasettet ["Bydelsinndeling"](https://data.norge.no/datasets/44f30e8d-b653-4463-9e78-73aa7fbcfdf0) har Los-tema `Bygg og eiendom `
a. Søk på `eiendom` gir 45 treff i datasettkatalogen, ingen av disse er datasettet "Bydelsinndeling"
b. Søk på `bygg og eiendom` gir 1478 treff.... 
c. Søk på `"bygg og eiendom"` gir 1478 treff...

**Comment by stigbd** [comment]
I datasett-dømet til Øystein, ser det slik ut (RDF):
```
https://data.norge.no/node/1115>
        a                         dcat:Dataset ;
        dcat:theme                <http://publications.europa.eu/resource/authority/data-theme/GOVE>, 
                                  <https://psi.norge.no/los/tema/bygg-og-eiendom> ;
.
```
Tanken er vel at at søket bør inkludere preflabel til hhv `data-theme/GOVE` og `tema/bygg-og-eiendom` som er hhv "Forvaltning og offentlig sektor" og "Bygg og eiendom" på norsk bokmål.

Spørsmålet er då: er disse prefLabels i basen til fdk-fulltext-search?

**Comment by shenluna** [comment]
Dette ble ikke tatt med ved forrige iterasjon av søk på portal. Se issue https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/228
Vi har satt opp møte for å spekke opp det som trengs for å komme videre.

**Comment by oystein-asnes** [comment]
Nå er jeg kanskje i ferd med å dra dette litt langt, men i rdf-en til Los-kategorien `Bygg og eiendom` ligger det (i selve vokabularet)  pref labels på nynorsk (`bygg og eigedom`) og engelsk (`building and property`). Her er det ingen kobling i fritekst-søk i dag. Her er det forresten også en mapping til `Regioner og byer` 
https://psi.norge.no/los/tema/bygg-og-eiendom.html

**Comment by oystein-asnes** [comment]
Mer av det samme via behovskøen til datafabrikken: https://github.com/datadeling/behov-issue-tracker/issues/73
