### ISSUE TITLE
Exception on /datasets (RSS-feed virker ikke)

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-fulltext-search#187]
RSS-feed virker ikke.
Har feilet siden 22/04, kl 22:13
(Sidenote; dette har ikke blitt plukket opp av error-reporting i GCP, indikerer at loggingen ikke er helt riktig her)

Kan se ut som vi har begynt å høste et datasett som ikke har nb-tittel?

> jsonPayload: {
> exc_info: "Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
>   File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 467, in wrapper
>     resp = resource(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 84, in view
>     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
>     resp = meth(*args, **kwargs)
>   File "/app/src/fdk_fulltext_search/endpoints.py", line 76, in get
>     return Response(response=create_feed(FeedType.RSS), mimetype=mimetype)
>   File "/app/src/fdk_fulltext_search/service/feed.py", line 42, in create_feed
>     feed_entry.title(translate(dataset["title"]))
>   File "/app/src/fdk_fulltext_search/service/feed.py", line 79, in translate
>     translatable["nb"]
> KeyError: 'nb'"

**Comment by tenstad** [comment]
Closed by https://github.com/Informasjonsforvaltning/fdk-fulltext-search/commit/b822b90c6300fd14f59d787aa23725d59c8f1931
