### ISSUE TITLE
Ingest fra høstere er ustabilt

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-fulltext-search#42]
Står i framsida:
![image](https://user-images.githubusercontent.com/1702357/82871786-60d56380-9f32-11ea-979b-886e4abd868d.png)

Klikker på "Kommunereform - API" og får "blank side" og 404 i konsollet:
![image](https://user-images.githubusercontent.com/1702357/82871898-87939a00-9f32-11ea-9b6e-2d56d6883633.png)

**Comment by rannveigskjerve** [comment]
Usikker på om dette er et problem med fulltext-search, da skulle alt som kommer derfra produsere det samme resultatet (altså 404), men ser på det.

**Comment by stigbd** [comment]
fulltext-search returnerer treffliste /recent. Første treff har ein id som ikkje fins i databasen. Sjekk skjermdump:
![image](https://user-images.githubusercontent.com/1702357/82876503-2d4a0780-9f39-11ea-920b-06f0fd5291ff.png)

**Comment by rannveigskjerve** [comment]
Ja, er på informationmodels generelt. siste ingest har ikke opdatert ID-er. Prøver å finne ut hvorfor.

**Comment by lillelars** [comment]
endret etter høstere er oppdatert. Lukker saken.
