### ISSUE TITLE
Loggen til fulltext vises ikke i gcp

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-fulltext-search#51]
Dette bør den!

**Comment by lillelars** [comment]
@valosnah er dette en oppgave for deg?

**Comment by jeffreiffers** [comment]
Jeg har verifisert at loggen til fulltext ligger i gcp. Jeg lukker saken.

**Comment by lillelars** [comment]
fikset for lenge siden. lukker saken.
