### ISSUE TITLE
Søk etter datasett gir ikke treff på distribusjonsnavn

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-fulltext-search#62]
Søk må gi treff på alt.
Det betyr hvis jeg har et søk "sparkesykkler" (ja med 2 k'er) :p, så må dette gi treff på datasettet: Nasjonalt rutedatasett for kollektivtrafikk i Norge
https://data.transportportal.no/datasets/f8327e57-60fa-440f-9ecd-a8765ca13ae6

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/f69f25b7-f27c-40c3-a5d0-a6fc619f9fce)

**Comment by rannveigskjerve** [comment]
Testet: gir treff både for delvis- og nøyaktif treff for tittel + formater på distribusjoner
