### ISSUE TITLE
Teststrategi for testing av vekting på søk

### ISSUE THREAD

**Issue by rannveigskjerve** [Informasjonsforvaltning/fdk-fulltext-search#69]
Kvaliteten på fulltext search er sterkt avhengig av vekting. Dette har vi nå løst med å teste vektinga via kontrakttester. Dette er en mulig løsning, men vi begynner nå å komme opp i et veldig høyt antall (73 and counting) kontrakttester. 

- [ ] undersøke alternativer for testinng av vekting på søk

**Comment by stigbd** [comment]
@NilsOveTen Kan du undersøke om dette issuet stadig er relevant?

**Comment by NilsOveTen** [comment]
@stigbd Det er fortsatt relevant, ja. Å forenkle vår logikk ang. vekting av søk vil _jeg_ tippe er beste løsning. Men tror vi bør samle alle til et lengre møte/brainstorming for å legge en plan for fulltext-search. Er ikke bare komplisert vekting av søk som er problem der, men kanskje det er det som er bakgrunnen for de fleste problemene :shrug:
