### ISSUE TITLE
full-text-search changes dcat:type 

### ISSUE THREAD

**Issue by rannveigskjerve** [Informasjonsforvaltning/fdk-fulltext-search#73]
Fulltext overskriver feltet 'type' med navnet på indexen. Dette bør flyttes til et tidligere tidspunkt, fulltext selv skal ikke manipulere data.

- [x] datasets
- [x] dataservices
- [x] concepts
- [x] informationmodels

**Comment by NilsOveTen** [comment]
fdk-rdf-parser legger til dette feltet for datatjenester og datasett, informasjonsmodeller og begrep må enten flyttes over til nytt høsteløp eller legge til feltet i høsteprosessen

**Comment by lillelars** [comment]
Denne er ferdigstilt av annen issue. Lukker saken
