### ISSUE TITLE
Støtte publisher med lenke til organization-catalogue

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-fulltext-search#78]
Vi må støtte at publisher har lenke til vår organization-catalogue, feks `https://organization-catalogue.fellesdatakatalog.digdir.no/organizations/974760673`

Det er min forståelse at dette kan løystast ved å oppgradere til siste versjon av fdk-rdf-parser.

Viktig fordi dcat-ap-no spesifserer at dette er anbefalt måte å lenke på:
https://data.norge.no/specification/dcat-ap-no/#Datasett-utgiver

**Comment by NilsOveTen** [comment]
Løst av https://github.com/Informasjonsforvaltning/fdk-fulltext-search/pull/79
