### ISSUE TITLE
Publisere openapi spec til data.norge.no

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-fulltext-search#94]

**Comment by NilsOveTen** [comment]
Hvis jeg husker korrekt så er det to ting som må gjøres for å få til dette:
- [ ] Fjerne test-url fra servers i openapi-spec
- [ ] Legge til `https://raw.githubusercontent.com/Informasjonsforvaltning/fdk-fulltext-search/master/fdk-fulltext-search-api.yaml` i dataservice-publisher
